### PR TITLE
Add color hint to materials

### PR DESCRIPTION
**Pull request by danielniccoli**
Code based on #220

### CODE REVIEW

**Comment by TwoAbove** [comment]
Cool! After you update https://github.com/TwoAbove/noita-tools/pull/220 can you, please, merge these together?

**Comment by TwoAbove** [comment]
Can you, please, rebase this on top of develop?

**Comment by TwoAbove** [comment]
So with dark mode, some colors are not visible, like gunpowder. Maybe adding a 'color-light' border would make this better? image

**Comment by danielniccoli** [comment]
With border-light

image

I added some borders to single dark materials by hand via browser dev console. If someone wants to add the effort, you could perhaps calculate the brightness of the color and add a border if the brightness is below a certain threshold.

image

> Can you, please, rebase this on top of develop?

I've never used rebase. Could you help me by telling what command I'd need to run?

**Comment by TwoAbove** [comment]
```
git remote add upstream https://github.com/TwoAbove/noita-tools.git
git fetch upstream
git rebase upstream/develop
git push --force
```
I think this is the correct way to do it

**Comment by danielniccoli** [comment]
These commands created a conflict, where oddly the incoming and current change looked like old code. I aborted the rebase.

I noticed that my fork was not updated with your changes, so I merged them. Maybe this is already what you needed?

**Comment by TwoAbove** [comment]
Perfect, thanks!

**Pull request merged**
